export const VITE_SEOUL_SEARCH_BASE_URL = import.meta.env.VITE_SEOUL_SEARCH_BASE_URL
export const VITE_SEOUL_SEARCH_KEY = import.meta.env.VITE_SEOUL_SEARCH_KEY
export const VITE_SEOUL_SEARCH_TYPE = import.meta.env.VITE_SEOUL_SEARCH_TYPE
export const VITE_SEOUL_SEARCH_SERVICE = import.meta.env.VITE_SEOUL_SEARCH_SERVICE
export const VITE_SEOUL_SEARCH_START_INDEX = import.meta.env.VITE_SEOUL_SEARCH_START_INDEX
export const VITE_SEOUL_SEARCH_END_INDEX = import.meta.env.VITE_SEOUL_SEARCH_END_INDEX